services:
  wohlsoft-ci-ubuntu2404-qt6:
    image: ghcr.io/wohlsoft/wohlsoft-ci-ubuntu2404-qt6
    build:
      context: .
      dockerfile: Docker-WohlSoft
    container_name: wohlsoft-ci-ubuntu2404-qt6
